name: CouponIt
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #Staggered Grid View
  flutter_staggered_grid_view: "^0.2.3"
  

  # UI PACKAGES
  color: any
  flutter_swiper: ^1.1.4
  flutter_page_indicator: ^0.0.3
  transformer_page_view: ^0.1.4
  unicorndial: ^1.1.5
  splashscreen: ^1.1.0
  flutter_spinkit: "^2.1.0"
  backdrop: ^0.1.8
  auto_size_text: ^0.2.1
  share: ^0.5.3
  pull_to_refresh: ^1.1.6
  image_picker: ^0.4.10
  intro_views_flutter: ^2.3.0
  flutter_custom_tabs: any
  flutter_signin_button: ^0.2.1
  flutter_auth_buttons: ^0.3.1
  random_color: ^1.0.3
  shimmer: ^0.0.6


  # FONT AWESOME ICONS
  font_awesome_flutter: ^8.0.1
  community_material_icon: any

  # QR Code Generator
  qr_flutter: any

  # URL LAUNCHER
  # - dependencies for url links to work
  url_launcher: any
  
  http: 0.12.0
  
  # BARCODE SCANNER MODULE
  barcode_scan: ^0.0.3
  
  # FIREBASE DEPENDENCIES
  google_sign_in: ^3.2.1
  firebase_core: any
  firebase_database: ^1.0.4
  firebase_auth: ^0.5.20

  # Push Notifications
  onesignal: ^1.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_launcher_icons: "^0.6.1"

flutter_icons:
  android: true 
  image_path: "assets/images/ic_couponitlogo_2.png"
  image_path_android: "assets/images/ic_couponitlogo_2.png"
  adaptive_icon_background: "#ff1f69"
  adaptive_icon_foreground: "assets/images/ic_couponitlogo_2 .png"
  



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/bg5.jpg
   - assets/images/bg4.jpg
   - assets/images/bg3.jpg
   - assets/images/bg2.jpg
   - assets/images/ic_couponitlogo.png
   - assets/images/ic_couponitlogo_2.png
   - assets/images/couponit_logo.png
   - assets/images/login_bg.jpg
   - assets/data/local_deals.json
   - assets/data/coupons.json
   - assets/images/bgGradient1.jpg
   - assets/images/bgGradient2.jpg
   - assets/images/bgGradient3.jpg
   - assets/images/bgGradient4.jpg
   - assets/images/bgGradient5.jpg
   - assets/images/bgGradient6.jpg
   - assets/images/bgGradient7.jpg
   - assets/images/bgGradient8.jpg
   - assets/images/bgGradient9.jpg
   - assets/images/image1.png
   - assets/images/image2.png
   - assets/images/image3.png
   - assets/images/image4.png
   - assets/images/image5.png
   - assets/images/sadface.png
   - assets/images/park.png
   - assets/images/friends.png
   - assets/images/friends3.png
   - assets/images/world.png
   - assets/images/loading.png
   - assets/images/loading_icon.png
   - assets/images/money.png
   - assets/images/slide1.jpg
   - assets/images/slide2.jpg
   - assets/images/slide3.jpg
   - assets/images/logo.png
   - assets/images/sephora.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf
    - family: Archivo
      fonts:
        - asset: assets/fonts/ArchivoBlack-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
    
          



  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
